crawler:
  fc2fan_local_path: null
  hardworking: true
  normalize_actress_name: true
  required_keys:
  - cover
  - title
  respect_site_avid: true
  selection:
    cid:
    - fanza
    fc2:
    - fc2
    - avsox
    - javdb
    - javmenu
    - fc2ppvdb
    getchu:
    - dl_getchu
    gyutto:
    - gyutto
    normal:
    - airav
    - avsox
    - javbus
    - javdb
    - javlib
    - jav321
    - mgstage
    - prestige
  sleep_after_scraping: PT1S
  use_javdb_cover: fallback
network:
  proxy_free:
    avsox: https://avsox.click
    javbus: https://www.seedmm.help
    javdb: https://javdb368.com
    javlib: https://www.y78k.com
  proxy_server: null
  retry: 3
  timeout: PT10S
other:
  auto_update: false
  check_update: true
  interactive: true
scanner:
  filename_extensions:
  - .3gp
  - .avi
  - .f4v
  - .flv
  - .iso
  - .m2ts
  - .m4v
  - .mkv
  - .mov
  - .mp4
  - .mpeg
  - .rm
  - .rmvb
  - .ts
  - .vob
  - .webm
  - .wmv
  - .strm
  - .mpg
  ignored_folder_name_pattern:
  - ^\.
  - ^#recycle$
  - "^#\u6574\u7406\u5B8C\u6210$"
  - "^#\u4E0D\u8981\u626B\u63CF$"
  ignored_id_pattern:
  - (144|240|360|480|720|1080)[Pp]
  - '[24][Kk]'
  - \w+2048\.com
  - Carib(beancom)?
  - '[^a-z\d](f?hd|lt)[^a-z\d]'
  input_directory: /path/to/input
  manual: true
  minimum_size: 232MiB
  skip_nfo_dir: true
summarizer:
  censor_options_representation:
  - "\u65E0\u7801"
  - "\u6709\u7801"
  - "\u6253\u7801\u60C5\u51B5\u672A\u77E5"
  cover:
    add_label: false
    basename_pattern: poster
    crop:
      engine: null
      on_id_pattern:
      - ^\d{6}[-_]\d{3}$
      - ^ARA
      - ^SIRO
      - ^GANA
      - ^MIUM
      - ^HHL
    highres: true
  default:
    actress: "#\u672A\u77E5\u5973\u4F18"
    director: "#\u672A\u77E5\u5BFC\u6F14"
    producer: "#\u672A\u77E5\u5236\u4F5C\u5546"
    publisher: "#\u672A\u77E5\u53D1\u884C\u5546"
    series: "#\u672A\u77E5\u7CFB\u5217"
    title: "#\u672A\u77E5\u6807\u9898"
  extra_fanarts:
    enabled: true
    scrap_interval: PT1.5S
  fanart:
    basename_pattern: fanart
  move_files: true
  nfo:
    basename_pattern: movie
    custom_genres_fields:
    - '{genre}'
    - '{censor}'
    custom_tags_fields:
    - '{genre}'
    - '{censor}'
    title_pattern: '{num} {title}'
  path:
    basename_pattern: '{num}'
    hard_link: false
    length_by_byte: true
    length_maximum: 250
    max_actress_count: 10
    output_folder_pattern: /path/to/output
  title:
    remove_trailing_actor_name: true
translator:
  engine: null
  fields:
    plot: true
    title: true
