version: "3.8"
services:
  javsp:
    build: .
    container_name: javsp
    environment:
      - TZ=Asia/Shanghai
      # 指定待处理视频输入目录（容器内路径）
      - INPUT_DIR=/video
      # 指定整理后输出目录（容器内路径）
      - OUTPUT_DIR=/output
    volumes:
      # 输入视频目录（只读挂载）
      - ./video:/video:ro
      # 元数据/封面等输出目录
      - ./output:/output
      # 可选：挂载自定义配置文件
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped